### ISSUE TITLE
Use NSCoder

### ISSUE THREAD

**Issue by iotize** [iotize/CSV#3]
Apple already provide a great interface for serializing object graphs. It would be a good idea to support encoding / decoding by [subclassing `NSCoder`](http://developer.apple.com/library/ios/#documentation/cocoa/Conceptual/Archiving/Articles/serializing.html).

It would also be a good idea to rename 'separatorChar' and 'newline' in terms of delimiters (e.g 'field delimiter' / 'record delimiter') using whichever names are appropriate with `NSCoder`.

**Comment by ryanmasondavies** [comment]
Now redundant!
